### ISSUE TITLE
Opening Excel (not Excelx) takes forever and is a memory hog

### ISSUE THREAD

**Issue by MasterSlowPoke** [roo-rb/roo#168] opened 2015-01-22 16:10 UTC
Just trying to run this line:
Roo::Excel.new('public/uploads/test.xls')

Test.xls is a simple, 33x10 spreadsheet. Roo is taking over 5 minutes to process it, and maxing out my system's memory. Obviously something is wrong.

I tried to try out roo-excel, but bundle was complaining that it required a roo version >2, which afaik never existed.

**Comment by stevendaniels** [comment] 2015-02-09 00:28
The issue you mentioned was previously fixed.

Roo version > 2 isn't available on RubyGems. It's only available on github. Add the following to your gemfile to install it.

    gem 'roo', :git => 'git://github.com:roo-rb/roo.git'

**Comment by stevendaniels** [comment] 2015-02-27 04:30
I recommend closing this issue.

**Comment by stevendaniels** [comment] 2015-03-23 01:52
~~I recommend closing this issue.~~

I verified the memory and speed issues exist in master. Even after #180, memory is still a big issue. When I opened a 750KB xlsx file, memory consumption balloons to 900MB. 

I need to take a closer and figure out what the root cause of the memory is.

**Comment by stevendaniels** [comment] 2015-04-25 07:28
Since this is an issue with Excel files, I've opened an issue in roo-xls. 

I'm closing this issue.

**Closed by stevendaniels** 2015-04-25 07:28 UTC
