### ISSUE TITLE
Memory error when opening file with 500k rows

### ISSUE THREAD

**Issue by MatthiasRMS** [roo-rb/roo#407] opened 2017-11-23 09:31 UTC
Hi,

I'm running into a memory issue when trying to work on a 500k rows XLSX file. 
Error thrown by Nokogiri:

Nokogiri::XML::XPath::SyntaxError: FATAL: Memory allocation failed : growing nodeset hit limit: growing nodeset hit limit

I don't think there is an easy workaround/solution.
I think the easiest way would be to split the spreadsheet in multiple smaller sheets containing about 10k rows. 

Is this possible with Roo ? Would you advise any other solution ?

Thanks

**Comment by motdotla** [comment] 2018-05-17 22:16
I've found `each_row_streaming` to be helpful with this. Also avoid use of `last_row`.

**Comment by motdotla** [comment] 2018-05-17 22:28
Nix that. slightly better but still terrible memory issues. See this thread: https://github.com/roo-rb/roo/issues/179

**Comment by tgturner** [comment] 2018-09-11 20:44
Duplicate of https://github.com/roo-rb/roo/issues/179

**Closed by tgturner** 2018-09-11 20:44 UTC
