### ISSUE TITLE
RuntimeError: Unknown Codepage 0x906c 

### ISSUE THREAD

**Issue by henb** [roo-rb/roo#144] opened 2014-08-16 16:52 UTC
See http://stackoverflow.com/questions/25231208/how-to-fix-the-error-in-spreadsheet-gem-unknown-codepage-0x906c

Please help fix this error!

**Comment by stevendaniels** [comment] 2015-02-11 02:49
This issue seems to affect an older version of Roo.
Have you been able to replicate the issue with the current version of Roo?

**Comment by stevendaniels** [comment] 2015-02-27 04:33
It's been two weeks without a response, I recommend closing this issue.

**Comment by stevendaniels** [comment] 2015-03-23 09:47
This issue was caused by spreadsheet gem, not roo. Closing this issue.

**Closed by stevendaniels** 2015-03-23 09:47 UTC
