### ISSUE TITLE
Freezes Pry (and probably irb)

### ISSUE THREAD

**Issue by charly** [roo-rb/roo#50] opened 2013-07-23 15:45 UTC
Hi,
And thanks for a great gem.

So if Roo::SomeSheetFormat.new('xls') somehow appears in pry, ruby shoots the processor at 99% and nothing happens.

Pry (irb on steroids) uses inspect to show the guts of an object. To avoid this nuisance you may add an inspect method on each Roo::SomeSheetFormat (or their super class if they have one), give it 2 words of info and it'll work fine.

**Comment by stevendaniels** [comment] 2015-02-11 13:08
This issue seems to affect an older version of Roo.
Have you been able to replicate the issue with the current version of Roo?

Roo::Base has an inspect method, so this should work now.
I recommend closing this issue.

**Comment by stevendaniels** [comment] 2015-03-10 12:10
@simonoff This issue affects an older version of pry. Please close this issue.

**Comment by stevendaniels** [comment] 2015-03-24 08:05
After playing around more, I've also seen an issue when using irb/pry.

The issue is here:

    # lib/roo/base.rb
    # call to_s method defined on subclasses
    def inspect
      to_s
    end

And then the subclasses define ```to_s``` like this

    # lib/roo/excelx.rb
    # shows the internal representation of all cells
    # for debugging purposes
    def to_s(sheet=nil)
      sheet_for(sheet).cells.inspect
    end

When using roo in the console, loading anything more than a trivial spreadsheet returns an absolutely huge object. It's so large it doesn't really help with debugging. 

Would it make sense to modify the ```inspect``` method like this?

     def inspect(debug = false)
       if debug
         to_s
       else
         "<##{ self.class }:#{ self.object_id.to_s(8) } #{ self.instance_variables.join(' ') }>"
       end
     end

**Comment by simonoff** [comment] 2015-03-24 20:11
I think yes.

**Closed** 2015-03-28 09:47 UTC
