### ISSUE TITLE
`parse` does not return header data

### ISSUE THREAD

**Issue by supremebeing7** [roo-rb/roo#424] opened 2018-04-22 17:44 UTC
Perhaps I am just trying to use this gem incorrectly, but I was attempting to `parse` a CSV file and the `parse` method gives all the data but with the header row stripped.

example gist: https://gist.github.com/supremebeing7/c027599ceff6a536e6b378dcb3e19782

Is that the expected behavior? I see I can convert `to_a` and it will show the header row, or I can access it with `row(1)`, but the `parse` thing threw me off and seemed like a bug. If that is the expected behavior, perhaps some clarity in the README would be helpful? Let me know if so and I'd be happy to add something.

**Comment by ej2015** [comment] 2018-07-19 08:37
Seems you already figured it out. For posterity, you can pass [headers: true](https://github.com/roo-rb/roo/blob/3ed05e1caef0ce3c5db5c19f1fa14e6f74193079/lib/roo/base.rb#L309) option.

**Comment by supremebeing7** [comment] 2018-07-19 16:30
Yep, I had that in my [example gist](https://gist.github.com/supremebeing7/c027599ceff6a536e6b378dcb3e19782#file-parser-rb-L10).

**Comment by tgturner** [comment] 2018-09-11 20:16
Closing because this is intended behavior and there is a PR open that would add documentation to the README to clarify any confusion.

**Closed by tgturner** 2018-09-11 20:16 UTC
