### ISSUE TITLE
`Roo::Formatters::CSV#to_csv` behavior with hyperlink seems to be wrong

### ISSUE THREAD

**Issue by vividmuimui** [roo-rb/roo#379] opened 2017-01-22 14:57 UTC
Hi, 
I'm not good at English, so I'm sorry if it is difficult for you to understand my English.

I use v.2.7.1.
`Roo::Formatters::CSV#to_csv` behavior with hyperlinks seems to be wrong.
Current behaivior is output `hyperlink` instead of `@value`.

# excel file

![excel](https://cloud.githubusercontent.com/assets/1803598/21837468/97e4cf3e-d80f-11e6-946a-2c8d1c0c212a.png)
https://github.com/vividmuimui/roo/blob/with_hyperlink_sample/with_hyperlink_sample.xlsx

```ruby
irb(main):001:0> require "roo"
=> true
irb(main):002:0> Roo::VERSION
=> "2.7.1"
irb(main):003:0> file = "/path/to/with_hyperlink_sample.xlsx"
=> "/path/to/with_hyperlink_sample.xlsx"
irb(main):004:0> excel = Roo::Excelx.new(file)
=> <#Roo::Excelx:1777751165347360 @tmpdir @shared @filename @sheet_files @sheet_names @sheets @sheets_by_name @options @cell @cell_type @cells_read @first_row @last_row @first_column @last_column @header_line>
irb(main):005:0> excel.map(&:itself)
=> [["mail"], ["example001@example.com"], ["example002@example.com"]]
irb(main):006:0> excel.sheet_for(nil).hyperlinks
=> {[2, 1]=>"mailto:example001@example.com", [3, 1]=>"mailto:example002@example.com"}
```

# Current `#to_csv` Behavior

```ruby
irb(main):007:0> excel.to_csv
=> "\"mail\"\n\"mailto:example001@example.com\"\n\"mailto:example002@example.com\"\n"
```

# Expected `#to_csv` Behavior

```ruby
irb(main):007:0> excel.to_csv
=> "\"mail\"\n\"example001@example.com\"\n\"example002@example.com\"\n"
```

# Other to_xxx methods behavior

```ruby
irb(main):008:0> excel.row(2).to_csv
=> "example001@example.com\n"
irb(main):009:0> excel.column(1).to_csv
=> "mail,example001@example.com,example002@example.com\n"
irb(main):010:0> excel.to_yaml
=> "--- \ncell_1_1: \n  row: 1 \n  col: 1 \n  celltype: string \n  value: mail \ncell_2_1: \n  row: 2 \n  col: 1 \n  celltype: link \n  value: example001@example.com \ncell_3_1: \n  row: 3 \n  col: 1 \n  celltype: link \n  value: example002@example.com \n"
# --- 
# cell_1_1: 
#   row: 1 
#   col: 1 
#   celltype: string 
#   value: mail 
# cell_2_1: 
#   row: 2 
#   col: 1 
#   celltype: link 
#   value: example001@example.com 
# cell_3_1: 
#   row: 3 
#   col: 1 
#   celltype: link 
#   value: example002@example.com 
```

**Comment by chopraanmol1** [comment] 2018-11-22 06:55
It is expected behavior. You can use `no_hyperlinks` options (#459 currently will only work on roo master, will be part of next release 2.7.1+ ) while creating an instance of Roo::Excelx to ignore hyperlinks altogether.

**Closed by chopraanmol1** 2018-11-22 06:55 UTC

**Comment by belisabettega** [comment] 2022-06-13 11:35
I'm having the same problem, but I'm using the roo version '2.5.1', so I believe I don't have access to the `no_hyperslinks` option when creating an instance of `Roo::Excelx`. Because my application is an old one I can't update the roo version... Does anyone has an idea on how to solve this error then?
