### ISSUE TITLE
Current first entry from Base#parse(headers: true) is a hash of the header row as both keys and values

### ISSUE THREAD

**Issue by Empact** [roo-rb/roo#62] opened 2013-08-18 09:45 UTC
Probably should just be skipped.

**Comment by stevendaniels** [comment] 2015-02-11 13:06
@Empact , does this issue with the current version of Roo?

**Comment by stevendaniels** [comment] 2015-03-10 12:13
Looks like this issue doesn't exist anymore. I recommend closing it.
```
# lib/roo/base.rb
  def each(options = {})
    if options.empty?
      1.upto(last_row) do |line|
        yield row(line)
      end
    else
      clean_sheet_if_need(options)
      search_or_set_header(options)
      headers = @headers ||
                Hash[(first_column..last_column).map do |col|
                  [cell(@header_line, col), col]
                end]

      @header_line.upto(last_row) do |line|
        yield(Hash[headers.map { |k, v| [k, cell(line, v)] }])
      end
    end
  end
```

**Comment by stevendaniels** [comment] 2015-03-26 23:09
This issue is stale. Closing.

**Comment by fredwu** [comment] 2016-03-15 04:57
@stevendaniels 

Hi, we just started using `roo` and found that this issue has not been resolved. In fact, when looking at the quoted code, `@headers` and `@header_line` are set correctly. However, `@header_line.upto(...` is causing the issue as the iterator is effectively iterating from the header line itself. Shouldn't it be `@header_line + 1` in this case?

**Comment by fredwu** [comment] 2016-03-15 08:25
By the way this specific behaviour is not tested. Tweaking the behaviour (to `@header_line +1`) only broke one high level test (`test/test_roo.rb:307`). Therefore I'm not sure what the intention of the behaviour should be...

**Comment by md5** [comment] 2016-06-13 19:08
I've just run into the same issue using version 2.4.0. I'm working around it with `each(headers).drop(1).each`

**Comment by theglauber** [comment] 2016-08-09 18:51
Same. Thanks for the "drop(1)" idea.

**Comment by frenkel** [comment] 2016-10-06 14:06
Same problem here. Is this intended behaviour @stevendaniels?

**Comment by stevendaniels** [comment] 2016-12-31 03:17
I'll need to look into this. @frenkel, @theglauber, @md5, @fredwu: 
Would any of you be able to add some test cases around this issue?

**Comment by frenkel** [comment] 2017-01-02 12:47
See commit above.

**Comment by stevendaniels** [comment] 2017-01-02 14:56
Thanks. I'll take a look.

**Comment by stevendaniels** [comment] 2017-01-03 02:30
Thanks again for the test cases @frenkel. I've merged these changes in.

**Closed** 2017-01-03 02:29 UTC
Labels: bug
